### ISSUE TITLE
feat: add support for Angular v11

### ISSUE THREAD

**Issue by JohannesHoppe** [kauppfbi/ngx-deploy-docker#70]
With the release of Angular 11, the `experimental` API to access the workspace has become stable.
This package depends on the experimental API and breaks.

https://github.com/kauppfbi/ngx-deploy-docker/blob/eca11c369822d35e4e275b4049feb482f342ec56/src/deploy/builder.ts#L6

As a reference, [this](https://github.com/angular/angularfire/commit/b976c5826a9417399d7a9aeab9560499d4d4be14) and [this](https://github.com/angular/angularfire/commit/7e1918a24653a21e46e8ce152ee1c23142684b62) will be useful.

You are also welcome to use this PR as a guide:
https://github.com/angular-schule/ngx-deploy-starter/pull/25

Please also rename `configuration` to `buildTarget`, too. 
https://github.com/kauppfbi/ngx-deploy-docker/blob/eca11c369822d35e4e275b4049feb482f342ec56/src/deploy/schema.json#L10
Because meanwhile, the CLI got configurations for `ng deploy` commands (which is NOT meant to be the configuration for the build as we did) @george43g pointed this out here: https://github.com/angular-schule/ngx-deploy-starter/discussions/1

**Comment by kauppfbi** [comment]
As mentioned in #97, the new release comes with support for v13, but not for older versions.

I will therefore close this issue since I do not plan to invest in backwards compatibility.
