### ISSUE TITLE
Adding ngx-deploy-docker fails after entering Docker username

### ISSUE THREAD

**Issue by rieckpil** [kauppfbi/ngx-deploy-docker#8]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Right after adding `ngx-deploy-docker` to my Angular 8.2.9 project and after entering the Docker username, I'm getting the following error:

```bash
➜  my-angular-app git:(master) ng add ngx-deploy-docker
Installing packages for tooling via npm.
+ ngx-deploy-docker@0.0.2
added 1 package from 1 contributor and audited 18850 packages in 11.378s
found 0 vulnerabilities

Installed packages for tooling via npm.
? What is your Docker username? rieckpil
ENOENT: no such file or directory, open '/Users/priecks/Desktop/junk/my-angular-app/node_modules/package.json'
``` 

## Expected behavior

Successfully add it to the Angular project.

## Minimal reproduction of the problem with instructions

- create new Angular app
- add it with `ng add ngx-deploy-docker`
- enter Docker username and hit enter

## Environment

<pre><code>
- Node: v12.9.1
- Angular: 8.2.9
- ngx-docker-deploy: 0.0.2
- OS: Mac

Others:
- I like turtles
</code></pre>

**Comment by kauppfbi** [comment]
Thank you for raising this issue, @rieckpil 🥇 

I see two possible issues causing this problem. 
The first is your `@angular-cli` version of 8.2.9. I just updated the readme, which tells you to use a version of `>=v8.3.0`.

Second is your OS... it is possible that the package behaves a bit differently on Mac, when it tries to open the file. I'll have to check that. 

Thank you, I will keep you updated 👍
